### ISSUE TITLE
Error when downloading by userid

### ISSUE THREAD

**Issue by YumekuiChaser** [Nekromateion/RedGifsDownloader#1]
I get the following error when trying to download by userid

![redgifs_error](https://user-images.githubusercontent.com/13459170/119973551-3b31ce80-bf79-11eb-8151-813d471fe7ad.png)

**Comment by Nekromateion** [comment]
Should be fixed in version 0.3

**Comment by YumekuiChaser** [comment]
As you said, working correctly with version 0.3
