### ISSUE TITLE
Feature Request - Categories

### ISSUE THREAD

**Issue by KaunWho** [Nekromateion/RedGifsDownloader#2]
By far the easiest downloader!
Can we have support to download to categories? These are available at: https://www.redgifs.com/categories

**Comment by Nekromateion** [comment]
From what I saw you can just put the name of the category in the search term option and it should work since it's pretty much the same thing.
I can add a seperate option for it though if you would prefer that.

**Comment by KaunWho** [comment]
Nah, if it the same think wouldn't want a line of code added. We can use that line for future features :)
